---
- name: Configure EC2 instance
  hosts: local
  connection: local
  gather_facts: false

  vars_files:
    - vars/vars.yml

  tasks:
    - name: Create EC2 instance
      import_tasks: tasks/ec2_create.yml

- name: Provision EC2 instance
  hosts: web
  remote_user: ubuntu
  become: true
  gather_facts: true

  vars_files:
    - vars/vars.yml

  pre_tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/user.yml
    - import_tasks: tasks/ssh.yml

  roles:
    - role: rvm.ruby
      rvm1_rubies: ['ruby-{{ ruby_version }}']
      rvm1_bundler_install: true
      rvm1_user: '{{ username | lower }}'

  tasks:
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/configs.yml
    - import_tasks: tasks/motd.yml
    - import_tasks: tasks/passenger_apache.yml
    - import_tasks: tasks/app_prep.yml
    - import_tasks: tasks/nodejs.yml
    - import_tasks: tasks/yarn.yml
    - import_tasks: tasks/prometheus.yml
    - import_tasks: tasks/harden.yml
    - import_tasks: tasks/restart.yml
      tags: restart
